version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: bdi
      MYSQL_PASSWORD: pepe1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql_data: